project_id = "vdbmlcaeqkbqbcynnbnf"

[functions.test-smtp-connection]
verify_jwt = false

[functions.verify-dns]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.smtp-worker]
verify_jwt = false